---
- hosts: webserver
  user: root
  gather_facts: False
  
  pre_tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    changed_when: False
    
  - name: Gather facts after Python is definitely present.
    setup:

  tasks:
  - name: install packages
    apt:
      name: ruby
      state: present
      update_cache: yes

  - name: install gems
    gem:
      name: "{{ item }}"
      include_doc: no
      state: present
    with_items:
      - sinatra

  - name: create folder
    file:
      dest: /var/www/ruby
      state: directory

  - name: copy webscript
    copy:
      src: files/webserver.rb
      dest: /var/www/ruby/webserver.rb

  - name: install rubyweb systemd unit file
    copy:
      src: rubyweb.service
      dest: /etc/systemd/system/rubyweb.service

  - name: make sure sinatra webapp is running
    systemd: 
      state: started
      name: rubyweb
      daemon_reload: yes
